In [1]:
from vnstock import *
import pandas as dp
from datetime import date, timedelta

In [2]:
from datetime import date, timedelta
import numpy as np
import pandas as pd

today = date.today()
quarter = round((today.month+1)/3 + 1/3)
year = today.year
ticker = 'fpt'

type = {1: 'incsta', 2: 'bsheet', 3: 'cashflow'}
numType = 1
times = 0

while True:
    url = f'https://s.cafef.vn/bao-cao-tai-chinh/{ticker}/{type[numType]}/{year}/{quarter}/0/0/ket-qua-hoat-dong-kinh-doanh-.chn'
    print(url)
    dfs = pd.read_html(url)
    if np.isnan(dfs[4].iloc[3,4]):
        quarter -= 1
        if quarter == 0:
            quarter = 4
            year -= 1
    else: break
    times += 1
    if times == 8: break

print('Done!')

https://s.cafef.vn/bao-cao-tai-chinh/fpt/incsta/2024/1/0/0/ket-qua-hoat-dong-kinh-doanh-.chn
https://s.cafef.vn/bao-cao-tai-chinh/fpt/incsta/2023/4/0/0/ket-qua-hoat-dong-kinh-doanh-.chn
https://s.cafef.vn/bao-cao-tai-chinh/fpt/incsta/2023/3/0/0/ket-qua-hoat-dong-kinh-doanh-.chn
Done!

In [3]:
format_table = ["Thông tin"]
format_table.extend(dfs[3].loc[0,1:4].tolist())

df = pd.DataFrame(columns= format_table, dtype='float32')
pd.options.display.float_format = '{:,}'.format

for i in range(len(dfs[4])):
    df.loc[len(df.index)] = (dfs[4].loc[i,0:4]).tolist()
df.set_index('Thông tin', inplace=True)
df = df.astype(float, copy=True)
df[df.abs() > 10000] = round(df[df.abs() > 10000] / 1000000000,2)
df

,Quý 4- 2022,Quý 1- 2023,Quý 2- 2023,Quý 3- 2023
Thông tin,,,,
1. Doanh thu bán hàng và cung cấp dịch vụ,"13,053.46","11,683.02","12,484.52","13,761.83"
2. Các khoản giảm trừ doanh thu,11.04,1.64,0.15,0.09
3. Doanh thu thuần về bán hàng và cung cấp dịch vụ (10 = 01 - 02),"13,042.43","11,681.38","12,484.36","13,761.74"
4. Giá vốn hàng bán,"7,801.15","7,113.5","7,850.54","8,265.38"
5. Lợi nhuận gộp về bán hàng và cung cấp dịch vụ(20=10-11),"5,241.27","4,567.88","4,633.82","5,496.37"
6. Doanh thu hoạt động tài chính,526.33,676.48,623.04,516.2
7. Chi phí tài chính,644.38,496.82,287.5,406.43
- Trong đó: Chi phí lãi vay,156.58,147.99,212.36,265.65
"8. Phần lãi lỗ trong công ty liên doanh, liên kết",98.2,43.76,-65.75,39.9
9. Chi phí bán hàng,"1,481.34","1,101.87","1,238.3","1,434.17"
10. Chi phí quản lý doanh nghiệp,"1,761.82","1,592.49","1,475.56","1,773.5"
11. Lợi nhuận thuần từ hoạt động kinh doanh{30=20+(21-22) + 24 - (25+26)},"1,978.26","2,096.93","2,189.77","2,438.36"
12. Thu nhập khác,67.0,42.88,46.98,46.85
13. Chi phí khác,56.24,19.17,18.61,56.06
14. Lợi nhuận khác(40=31-32),10.77,23.71,28.37,-9.21
15. Tổng lợi nhuận kế toán trước thuế(50=30+40),"1,989.03","2,120.64","2,218.13","2,429.15"
16. Chi phí thuế TNDN hiện hành,335.96,308.33,337.91,344.6
17. Chi phí thuế TNDN hoãn lại,33.17,2.51,24.65,8.69
18. Lợi nhuận sau thuế thu nhập doanh nghiệp(60=50-51-52),"1,619.89","1,809.8","1,855.58","2,075.87"
19. Lợi nhuận sau thuế công ty mẹ,"1,351.6","1,493.56","1,509.22","1,739.34"
20. Lợi nhuận sau thuế công ty mẹ không kiểm soát,268.29,316.24,346.36,336.53
21. Lãi cơ bản trên cổ phiếu(*),"1,235.0","1,361.0","1,373.0","1,373.0"
22. Lãi suy giảm trên cổ phiếu (*),"1,235.0","1,361.0","1,373.0","1,373.0"

In [15]:
def get_financial_info_from_CafeF(ticker, numType):
    today = date.today()
    quarter = round((today.month+1)/3 + 1/3)
    year = today.year
    ticker = ticker.lower()

    type = {1: 'incsta', 2: 'bsheet', 3: 'cashflow'}
    times = 0

    while True:
        quarter -= 1
        if quarter == 0:
            quarter = 4
            year -= 1
        
        url = f'https://s.cafef.vn/bao-cao-tai-chinh/{ticker}/{type[numType]}/{year}/{quarter}/0/0/ket-qua-hoat-dong-kinh-doanh-.chn'
        print(url)
        dfs = pd.read_html(url)
        if not np.isnan(dfs[4].iloc[3,4]):
            break   
            
        times += 1
        if times == 4: break

    format_table = ["Thông tin"]
    format_table.extend(dfs[3].loc[0,1:4].tolist())
    print(format_table)
    df = pd.DataFrame(columns= format_table, dtype='float32')
    pd.options.display.float_format = '{:,.2f}'.format

    for i in range(len(dfs[4])):
        df.loc[len(df.index)] = (dfs[4].loc[i,0:4]).tolist()
    df.set_index('Thông tin', inplace=True)

    df = df.astype(float, copy=True)

    df[df.abs() > 10000] = round(df[df.abs() > 10000] / 1000000000,4)

    return df

In [19]:
df = get_financial_info_from_CafeF('FPT',2)

https://s.cafef.vn/bao-cao-tai-chinh/fpt/bsheet/2023/4/0/0/ket-qua-hoat-dong-kinh-doanh-.chn
https://s.cafef.vn/bao-cao-tai-chinh/fpt/bsheet/2023/3/0/0/ket-qua-hoat-dong-kinh-doanh-.chn
['Thông tin', 'Quý 4- 2022', 'Quý 1- 2023', 'Quý 2- 2023', 'Quý 3- 2023']

,Quý 4- 2022,Quý 1- 2023,Quý 2- 2023,Quý 3- 2023
Thông tin,,,,
TÀI SẢN,-,-,-,-
A- TÀI SẢN NGẮN HẠN,"30,933.92","29,524.49","38,758.40","39,531.94"
I. Tiền và các khoản tương đương tiền,"6,440.18","3,289.42","6,236.48","7,153.63"
1. Tiền,"3,880.86","3,068.01","4,116.50","4,868.73"
2. Các khoản tương đương tiền,"2,559.32",221.41,"2,119.98","2,284.89"
...,...,...,...,...
13. Lợi ích cổ đông không kiểm soát,"4,310.62","4,472.36","4,444.63","4,771.57"
II. Nguồn kinh phí và quỹ khác,2.75,2.75,2.75,2.75
1. Nguồn kinh phí,2.75,2.75,2.75,2.75
2. Nguồn kinh phí đã hình thành TSCĐ,-,-,-,-
TỔNG CỘNG NGUỒN VỐN,"51,655.41","50,741.16","60,556.69","62,112.68"

In [35]:
df.iloc[0,0]

nan